### ISSUE TITLE
why should you make a apk instead?

### ISSUE THREAD

**Issue by fusaYT** [VDavid003/sm64-port-android-base#1]
Nintendo CANT ban it then make it a download apk! im waiting

**Comment by VDavid003** [comment]
First of all, an apk would contain parts of the original ROM which Nintendo wouldn't be happy about, second even the pc port has a license it it that prevents people from sharing compiled binaries. When the PC port was released Nintendo started taking down compiled binaries (an APK would be a compiled binary), so I'm not taking any chances.
