### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by juamnitruh** [VDavid003/sm64-port-android-base#12]
When i type "make --jobs 4", it starts the thing, but then it shows:
"make: *** duping jobs pipe: Bad file descriptor.  Stop."
I dont know what to do.
I'm using termux.

**Comment by VDavid003** [comment]
Can you tell me your Android version, architecture, and phone/device's name and exact steps you did to get this?
This error is not too descriptive.

**Comment by juamnitruh** [comment]
Lg k10, android 7.0, 32bits. I did everything normally. Actually, i
remember it working like 2 days ago, but i didnt know where my apk was, and
i uninstalled termux D: Now i tried it again (knowing how to get the apk)
and it didnt work :((

Em ter, 25 de ago de 2020 7:11 PM, VDavid003 <notifications@github.com>
escreveu:

**Comment by VDavid003** [comment]
Nothing was changed in the last 2 days, and in the last 3 days there was only one change and that one was tested on many different android versions and architectures by me, so I'd say this is some user error. I have no idea though as I can't find anything about it. Btw the apk is in the path listed in the last step of the guide, inside your Termux home directory in sm64-port-android.

**Comment by juamnitruh** [comment]
Oh well... I will try another rom, maybe its just my rom being bad..
 Thanks for the replying anyway :)

Em ter, 25 de ago de 2020 7:30 PM, VDavid003 <notifications@github.com>
escreveu:
