### ISSUE TITLE
Error when trying to start Gradle Build

### ISSUE THREAD

**Issue by Fra078** [VDavid003/sm64-port-android-base#13]
Platform Windows. When I try to start gradle build with _gradlew.bat assembleDebug_ it give this error.
Task :app:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\fp782\AppData\Local\Android\Sdk\ndk\21.3.6528147\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\fp782\Desktop\SM64\android\sm64-port-android-base\app\jni\Android.mk NDK_APPLICATION_MK=C:\Users\fp782\Desktop\SM64\android\sm64-port-android-base\app\jni\Application.mk APP_ABI=x86_64 NDK_ALL_ABIS=x86_64 NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/fp782/Desktop/SM64/android/sm64-port-android-base/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\fp782\Desktop\SM64\android\sm64-port-android-base\app\build\intermediates\ndkBuild\debug\lib -j4 APP_PLATFORM=android-16 C:/Users/fp782/Desktop/SM64/android/sm64-port-android-base/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/libmain.so}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
17 actionable tasks: 1 executed, 16 up-to-date

**Comment by VDavid003** [comment]
Aren't there other errors further up in the command line?

**Comment by VDavid003** [comment]
Closed due to no reply and no way for me to know the issue from this.
