### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by IndevBuildsIncognito** [VDavid003/sm64-port-android-base#14]
I suggest you change ./getSDL.sh to ```bash getSDL.sh``` some people won't understand what you put there and ```chmod 777 /data/data/com.termux -R``` isn't a bad advice as you said it allows you to get access to the APK file with ES File Explorer Pro or whatever file manager that can go to that directory this is for unrooted devices I also suggest this 
#Example
```cp /storage/emulated/0/baserom.us.z64 ./baserom.us.z64``` this is if you don't have a sdcard this will locate the ROM in your internal storage
You're dealing with kids that need really easy instructions I basically helped someone with this

**Comment by IndevBuildsIncognito** [comment]
This is for the termux build

**Comment by IndevBuildsIncognito** [comment]
Just to put it really simple for these kids
Do this in termux
-
```pkg install git wget make python getconf zip apksigner clang```
```git clone https://github.com/VDavid003/sm64-port-android --branch termux_build```
```cd sm64-port-android```
```termux-setup-storage```
#Example locates to Internal Storage
```cp /storage/emulated/0/baserom.us.z64 ./baserom.us.z64``` 
#Use bash command
```bash getSDL.sh```
#Extracts assets and builds apk
```make --jobs 4```
#Shows directory for unrooted users ES File Explorer recommend
cd --
pwd
chmod 777 /data/data/com.termux -R
I helped alot with this

**Comment by IndevBuildsIncognito** [comment]
By the way your app lags

**Comment by IndevBuildsIncognito** [comment]
![Screenshot_20200826-145356](https://user-images.githubusercontent.com/64507448/91344556-1327fb80-e7ac-11ea-999b-c386f15703df.png)
There we go

**Comment by VDavid003** [comment]
chmod 777 is a bad advice since making every file have all permissions is a security nightmare. Also, the AOSP built-in file manager sees Termux files properly, no root or 3rd party apps needed.
Btw kids will have it much easier when the builder is finished.

**Comment by fusaYT** [comment]
e
