### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by WallanceLMM** [VDavid003/sm64-port-android-base#15]
Hello, I just have a problem with MSYS2. I'm following the instructions, but I got stuck in "Copy in your baserom", the program thinks that the file or directory "/home/User/sm64-port-android-base/app/jni/src/baserom.us.z64" doesn't exist, what can I do?

**Comment by VDavid003** [comment]
What is the exact command that you entered?

**Comment by WallanceLMM** [comment]
cp /path/to/your/baserom.z64 ./app/jni/src/baserom.us.z64

**Comment by WallanceLMM** [comment]
cp /home/User/baserom.z64 ./home/User/sm64-port-android-base/app/jni/src/baserom.us.z64

**Comment by VDavid003** [comment]
you have a dot before "/home/User/sm64-port-android-base/app/jni/src/baserom.us.z64"
delete that, and it will work!

**Comment by WallanceLMM** [comment]
seems like nothing happens

**Comment by VDavid003** [comment]
it shouldn't say anything if it's successful
