### ISSUE TITLE
Compilation error (Nightly + Render96 1.4.2)

### ISSUE THREAD

**Issue by stranno** [VDavid003/sm64-port-android-base#16]
I'm getting this error compiling Render96 + 60FPS patch.

> Traceback (most recent call last):
  File "tools/mkzip.py", line 20, in <module>
    with zipfile.ZipFile(sys.argv[2], 'w', allowZip64=False) as zipf:
  File "/usr/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
IsADirectoryError: [Errno 21] Is a directory: 'build/us_pc/res/'
Makefile:705: recipe for target 'build/us_pc/res/' failed
make: *** [build/us_pc/res/] Error 1

I have no problems compiling the EX_Nightly alone (or patched for 60FPS) or the Render96 PC build. But I have troubles to build the Android Render96 Patched.

**Comment by VDavid003** [comment]
If you are building on PC, please try updating the repo inside app/jni/src to the latest commit, I haven't updated the submodule yet.

**Comment by stranno** [comment]
Thank you for your feedback.

With updated branch now I'm getting an SDL2 error.

> enhancements/render96_android.patch:126: trailing whitespace.
    BACKEND_CFLAGS += -DHAVE_SDL2=1
warning: 1 line adds whitespace errors.

I have executed the SDL2 install script both in the Android base and in the jni/src repo. No difference.

I can compile it but final binary throws a sound/sequences.bin error.

**Comment by VDavid003** [comment]
sound/sequences.bin means it can't find base.zip.
Did you copy it to Android/data/com.vdavid003.sm64port/files?

**Comment by stranno** [comment]
Wops. I forgot that I built the game with EXTERNAL_DATA. You're right. Now it works properly.

Is this error expected?

Thank you again.

**Comment by VDavid003** [comment]
The sequences.bin one is, and I knew about the first one, I'll close this once I get home to update the submodule!

**Comment by VDavid003** [comment]
Submodule updated!
