### ISSUE TITLE
NOWDRAWDISTANCE, BETTERCAMERA and TOUCH_CONTROLS flags dont seem to work

### ISSUE THREAD

**Issue by stranno** [VDavid003/sm64-port-android-base#18]
I have tried disabling them in the Make and using the flags and I can't make them work. Camera is still the Nintendo 64 camera, draw distance is the same and virtual controls are still there.

TOUCH_CONTROLS ?= 0
BETTERCAMERA ?= 1
NODRAWINGDISTANCE ?= 1

or make NODRAWDISTANCE=1 BETTERCAMERA=1 TOUCH_CONTROLS=0 TEXTSAVES=1 EXTERNAL_DATA=1 LEGACY_RES=1 -j4

Am I doing something wrong?

**Comment by milesthecreator** [comment]
I also have the same problem, I assume the options are broken?

**Comment by rbeesley** [comment]
TOUCH_CONTROLS is hard coded right now. There are two different patches way to fix this. There is a fork which makes them automatically hide if there is a controller present and being used and I also made a branch which makes TOUCH_CONTROLS toggleable, but that doesn't seem as valuable if the automatic control hiding is added. Regarding the other flags, I haven't looked.

**Comment by TechdudeGames** [comment]
I believe if you want to make the project with NODRAWDISTANCE or any other features you will have to add the flags for them to the Android.mk in app/jni.

**Comment by sheriff02** [comment]
> this. There is a fork which makes them automatically hide if there is a controller present and being used and I also made a branch which makes TOUCH_CONTROLS toggleable, but that doesn't seem as valuable if the automatic control

How to install fork with automaticaly disabled ouch controls? please, i dont understand

**Comment by stranno** [comment]
> I believe if you want to make the project with NODRAWDISTANCE or any other features you will have to add the flags for them to the Android.mk in app/jni. This was how I got EXTERNAL_DATA=1 to work on the ex branch at least.
Right. It was explained at the bottom part of the README since the beginning. I missed that when I compiled the game.

Thanks and sorry for the late response, I was not following the issue.

Closed.
