### ISSUE TITLE
Create a Dockerfile to ease build process

### ISSUE THREAD

**Issue by mkst** [VDavid003/sm64-port-android-base#3]
[Docker](https://www.docker.com/) allows for images to be created an ran on host machines in a similar manner to a VM, but without most of the associated performance hits.

The SM64 repository has a Docker image that wraps up all the build tools into an image, so performing the build is a single step, and the host machine is not polluted by any of the dependencies required for the build.

Reducing barriers to building helps reducing barriers for collaboration. I think a Dockerfile would be a nice addition to this repo.

**Comment by VDavid003** [comment]
Great idea, will check it out asap and pull it!
