### ISSUE TITLE
How do you disable overlay buttons on android?

### ISSUE THREAD

**Issue by Fredolx** [VDavid003/sm64-port-android-base#40]

**Comment by opjair29** [comment]
Change the line in sm64-port-android-base\app\jni\src Android.mk
TOUCH_CONTROLS ?= 1 to 0

**Comment by goldeneyeonline** [comment]
Should this work on the Android-Build-Process as well?
Neither charging the value in Android.mk nor saying "make TOUCH_CONTROLS=0 --jobs 4" makes the on screen controls vanish :-(
