### ISSUE TITLE
60fps_ex patch makes the button B (and puppycam) trigger everywhere on the screen

### ISSUE THREAD

**Issue by Nama** [VDavid003/sm64-port-android-base#47]
I tried alot and finally found out, that [this](https://github.com/VDavid003/sm64-port-android/blob/ex/nightly/enhancements/60fps_ex.patch) patch makes every tap on the screen trigger the button B and move the camera (puppycamera).
Moving, jumping, in the menu - always.

I'm building on termux on the ex/nightly branch.

**Comment by AndGuz** [comment]
Hi, I had this problem too but I solved it by modifying all the values of the control layout file to FFFF. Maybe if the developers puts the default values of the control layout to FFFF.

**Comment by AndGuz** [comment]
The problem is on the sm64-pc source because it has a default controller layout with some keys corresponding to the screen.

**Comment by Mikel8080** [comment]
What is that file you changed? not sure if I'm suffering by the same problem. ? I'd like to test the change. What it happens to me is when I press Analog Up + Jump button it's like jump + Z, they both individually works as it's supposed.

**Comment by AndGuz** [comment]
I edited the config file that contains the controller settings. Sorry for responding too late

**Comment by AndGuz** [comment]
that file is the one that contains default configurations. This one: https://github.com/VDavid003/sm64-port-android/blob/master/src/pc/configfile.c

**Comment by AndGuz** [comment]
after the 32th line are the default configurations, and if you change the value to 0xFF (i think the equivalent to FFFF) then the touch controls works perfectly

**Comment by AndGuz** [comment]
ill make a issue on that repo, so VDavid003 can fix it

**Comment by JLiveOf** [comment]
this issue comes from the code itself because i have a tablet pc with windows and in the pc port same happens when you touch the screen with the ext menu patch, i tried use the 60fps patch and when i touched the screen nothing happent
