### ISSUE TITLE
Failed to extract assets

### ISSUE THREAD

**Issue by Lumince** [VDavid003/sm64-port-android-base#59]
While compiling this in Termux I get this error below. Ive followed the instructions to the T. I even tried using the android builder and it still fails. This was my last choice since building android on windows or linux complains about a lib++_shared.so missing... Not sure what I could be doing wrong on any of these...

CANNOT LINK EXECUTABLE "gcc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
make: *** [Makefile:66: n64graphics] Error 1
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sm64-port-android/./extract_assets.py", line 292, in <module>
    main()
  File "/data/data/com.termux/files/home/sm64-port-android/./extract_assets.py", line 162, in main
    subprocess.check_call(
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:183: *** Failed to extract assets.  Stop.

**Comment by Deadiy** [comment]
Try doing the following:

apt-get update -y

apt-get upgrade -y

Then if any options appear do n

Then retry

**Comment by GreatGlisssor** [comment]
I Did That But There's No Option What Am I Going To Do????????

**Comment by GreatGlisssor** [comment]
Is There Another Way?????
