### ISSUE TITLE
Cant compile on termux

### ISSUE THREAD

**Issue by Nottoknow2** [VDavid003/sm64-port-android-base#64]
![Screenshot_20220214-105555_Termux](https://user-images.githubusercontent.com/65305457/153899673-2fe8209c-539a-4d3e-b379-7f5e5ec33304.jpg)
Termux android 12 compile error

**Comment by Algiuxs** [comment]
Run the following
```
pkg update
pkg upgrade
pkg install which binutils wget
make -j $(nproc)
cd tools/audiofile
make
cd ../..
make -j $(nproc)
```
If you get something about sdl2 missing run this
```
./getSDL.sh
```
Make sure to have external data ?= 0 in the Makefile if you have higher than an android 11 phone.
